# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from functions import Functions
import yukleniyor as yukleniyorPencere
import dortluyap as dortluyap
import ikiliyap as ikiliyap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 975)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(980, 975))
        MainWindow.setMaximumSize(QtCore.QSize(980, 975))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);border:0;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 958, 941))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ana_vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ana_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.ana_vertical_layout.setObjectName("ana_vertical_layout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.logo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.logo.setMinimumSize(QtCore.QSize(480, 100))
        self.logo.setMaximumSize(QtCore.QSize(480, 100))
        self.logo.setObjectName("logo")
        self.gridLayout_2.addWidget(self.logo, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.ana_vertical_layout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 11, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 13, 1, 1, 1)
        self.sinif_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sinif_line.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sinif_line.setFont(font)
        self.sinif_line.setStyleSheet("QLineEdit{\n"
"\n"
"border: 3px solid;\n"
"border-color:rgb(17, 124, 202);\n"
"border-radius:15px\n"
"\n"
"}")
        self.sinif_line.setText("")
        self.sinif_line.setAlignment(QtCore.Qt.AlignCenter)
        self.sinif_line.setObjectName("sinif_line")
        self.gridLayout.addWidget(self.sinif_line, 4, 2, 1, 1)
        self.lot_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lot_line.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lot_line.setFont(font)
        self.lot_line.setStyleSheet("QLineEdit{\n"
"\n"
"border: 3px solid;\n"
"border-color:rgb(17, 124, 202);\n"
"border-radius:15px\n"
"\n"
"}")
        self.lot_line.setAlignment(QtCore.Qt.AlignCenter)
        self.lot_line.setObjectName("lot_line")
        self.gridLayout.addWidget(self.lot_line, 8, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.double_color_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.double_color_checkBox.setFont(font)
        self.double_color_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.double_color_checkBox.setStyleSheet("color: rgb(4, 155, 224);")
        self.double_color_checkBox.setObjectName("double_color_checkBox")
        self.verticalLayout.addWidget(self.double_color_checkBox)
        self.sample_mod_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sample_mod_checkBox.setFont(font)
        self.sample_mod_checkBox.setAcceptDrops(False)
        self.sample_mod_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sample_mod_checkBox.setStyleSheet("color: rgb(4, 155, 224);")
        self.sample_mod_checkBox.setObjectName("sample_mod_checkBox")
        self.verticalLayout.addWidget(self.sample_mod_checkBox)
        self.box_test_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.box_test_checkBox.setFont(font)
        self.box_test_checkBox.setAcceptDrops(False)
        self.box_test_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.box_test_checkBox.setStyleSheet("color: rgb(4, 155, 224);")
        self.box_test_checkBox.setObjectName("box_test_checkBox")
        self.verticalLayout.addWidget(self.box_test_checkBox)
        self.gridLayout.addLayout(self.verticalLayout, 13, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: rgb(4, 155, 224);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color:#049BE0;\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(4, 155, 224);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(62, 198, 247);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 13, 2, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 7, 0, 1, 1)
        self.parti_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.parti_label.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.parti_label.setFont(font)
        self.parti_label.setStyleSheet("color: rgb(4, 155, 224);")
        self.parti_label.setAlignment(QtCore.Qt.AlignCenter)
        self.parti_label.setObjectName("parti_label")
        self.gridLayout.addWidget(self.parti_label, 2, 0, 1, 1)
        self.aciklama_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.aciklama_label_2.setFont(font)
        self.aciklama_label_2.setStyleSheet("color: rgb(4, 155, 224);")
        self.aciklama_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.aciklama_label_2.setObjectName("aciklama_label_2")
        self.gridLayout.addWidget(self.aciklama_label_2, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 9, 0, 1, 1)
        self.acklama_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.acklama_line.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.acklama_line.setFont(font)
        self.acklama_line.setStyleSheet("QLineEdit{\n"
"\n"
"border: 3px solid;\n"
"border-color:rgb(17, 124, 202);\n"
"border-radius:15px\n"
"\n"
"}")
        self.acklama_line.setText("")
        self.acklama_line.setAlignment(QtCore.Qt.AlignCenter)
        self.acklama_line.setObjectName("acklama_line")
        self.gridLayout.addWidget(self.acklama_line, 0, 4, 1, 1)
        self.ulke_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ulke_line.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ulke_line.setFont(font)
        self.ulke_line.setStyleSheet("QLineEdit{\n"
"\n"
"border: 3px solid;\n"
"border-color:rgb(17, 124, 202);\n"
"border-radius:15px\n"
"\n"
"}")
        self.ulke_line.setText("")
        self.ulke_line.setAlignment(QtCore.Qt.AlignCenter)
        self.ulke_line.setObjectName("ulke_line")
        self.gridLayout.addWidget(self.ulke_line, 0, 2, 1, 1)
        self.ulke_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ulke_label.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ulke_label.setFont(font)
        self.ulke_label.setStyleSheet("color: rgb(4, 155, 224);")
        self.ulke_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ulke_label.setObjectName("ulke_label")
        self.gridLayout.addWidget(self.ulke_label, 0, 0, 1, 1)
        self.size_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.size_label.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.size_label.setFont(font)
        self.size_label.setStyleSheet("color: rgb(4, 155, 224);")
        self.size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.size_label.setObjectName("size_label")
        self.gridLayout.addWidget(self.size_label, 6, 0, 1, 1)
        self.parti_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.parti_line.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.parti_line.setFont(font)
        self.parti_line.setStyleSheet("QLineEdit{\n"
"\n"
"border: 3px solid;\n"
"border-color:rgb(17, 124, 202);\n"
"border-radius:15px\n"
"\n"
"}")
        self.parti_line.setText("")
        self.parti_line.setAlignment(QtCore.Qt.AlignCenter)
        self.parti_line.setObjectName("parti_line")
        self.gridLayout.addWidget(self.parti_line, 2, 2, 1, 1)
        self.sa_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sa_label.setFont(font)
        self.sa_label.setStyleSheet("color: rgb(4, 155, 224);")
        self.sa_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sa_label.setObjectName("sa_label")
        self.gridLayout.addWidget(self.sa_label, 12, 0, 1, 1)
        self.size_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.size_line.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.size_line.setFont(font)
        self.size_line.setStyleSheet("QLineEdit{\n"
"\n"
"border: 3px solid;\n"
"border-color:rgb(17, 124, 202);\n"
"border-radius:15px\n"
"\n"
"}")
        self.size_line.setText("")
        self.size_line.setAlignment(QtCore.Qt.AlignCenter)
        self.size_line.setObjectName("size_line")
        self.gridLayout.addWidget(self.size_line, 6, 2, 1, 1)
        self.dosya_sec_pushbutton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dosya_sec_pushbutton.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dosya_sec_pushbutton.setFont(font)
        self.dosya_sec_pushbutton.setStyleSheet("QPushButton {\n"
"color: rgb(4, 155, 224);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color:#049BE0;\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(4, 155, 224);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(62, 198, 247);\n"
"}")
        self.dosya_sec_pushbutton.setObjectName("dosya_sec_pushbutton")
        self.gridLayout.addWidget(self.dosya_sec_pushbutton, 2, 4, 1, 1)
        self.sinif_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sinif_label.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sinif_label.setFont(font)
        self.sinif_label.setStyleSheet("color: rgb(4, 155, 224);")
        self.sinif_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sinif_label.setObjectName("sinif_label")
        self.gridLayout.addWidget(self.sinif_label, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.standartRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.standartRadio.setFont(font)
        self.standartRadio.setStyleSheet("color: rgb(17, 124, 202);")
        self.standartRadio.setObjectName("standartRadio")
        self.horizontalLayout_2.addWidget(self.standartRadio)
        self.arcRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.arcRadio.setFont(font)
        self.arcRadio.setStyleSheet("color: rgb(17, 124, 202);")
        self.arcRadio.setObjectName("arcRadio")
        self.horizontalLayout_2.addWidget(self.arcRadio)
        self.gridLayout.addLayout(self.horizontalLayout_2, 12, 2, 1, 1)
        self.aciklama_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.aciklama_label.setFont(font)
        self.aciklama_label.setStyleSheet("color: rgb(4, 155, 224);")
        self.aciklama_label.setAlignment(QtCore.Qt.AlignCenter)
        self.aciklama_label.setObjectName("aciklama_label")
        self.gridLayout.addWidget(self.aciklama_label, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 5, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 3, 0, 1, 1)
        self.parti_eleman_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.parti_eleman_line.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.parti_eleman_line.setFont(font)
        self.parti_eleman_line.setStyleSheet("QLineEdit{\n"
"\n"
"border: 3px solid;\n"
"border-color:rgb(17, 124, 202);\n"
"border-radius:15px\n"
"\n"
"}")
        self.parti_eleman_line.setAlignment(QtCore.Qt.AlignCenter)
        self.parti_eleman_line.setObjectName("parti_eleman_line")
        self.gridLayout.addWidget(self.parti_eleman_line, 10, 2, 1, 1)
        self.lot_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lot_label.setFont(font)
        self.lot_label.setStyleSheet("color: rgb(4, 155, 224);")
        self.lot_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lot_label.setObjectName("lot_label")
        self.gridLayout.addWidget(self.lot_label, 8, 0, 1, 1)
        self.parti_eleman_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.parti_eleman_label.setFont(font)
        self.parti_eleman_label.setStyleSheet("color: rgb(4, 155, 224);")
        self.parti_eleman_label.setAlignment(QtCore.Qt.AlignCenter)
        self.parti_eleman_label.setObjectName("parti_eleman_label")
        self.gridLayout.addWidget(self.parti_eleman_label, 10, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 1, 0, 1, 1)
        self.resimbilgi_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resimbilgi_label.setFont(font)
        self.resimbilgi_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.resimbilgi_label.setText("")
        self.resimbilgi_label.setObjectName("resimbilgi_label")
        self.gridLayout.addWidget(self.resimbilgi_label, 3, 4, 1, 1)
        self.ana_vertical_layout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 980, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu_coklu = QtWidgets.QMenu(self.menuBar)
        self.menu_coklu.setObjectName("menu_coklu")
        MainWindow.setMenuBar(self.menuBar)
        self.menu_ikili = QtWidgets.QAction(MainWindow)
        self.menu_ikili.setObjectName("menu_ikili")
        self.menu_dortlu = QtWidgets.QAction(MainWindow)
        self.menu_dortlu.setObjectName("menu_dortlu")
        self.menu_altili = QtWidgets.QAction(MainWindow)
        self.menu_altili.setObjectName("menu_altili")
        self.menu_sekizli = QtWidgets.QAction(MainWindow)
        self.menu_sekizli.setObjectName("menu_sekizli")
        self.menu_coklu.addAction(self.menu_ikili)
        self.menu_coklu.addSeparator()
        self.menu_coklu.addAction(self.menu_dortlu)
        self.menu_coklu.addSeparator()
        self.menu_coklu.addAction(self.menu_altili)
        self.menu_coklu.addSeparator()
        self.menu_coklu.addAction(self.menu_sekizli)
        self.menuBar.addAction(self.menu_coklu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.menu_dortlu.triggered.connect(self.dortluMenuAc)
        self.menu_ikili.triggered.connect(self.ikiliMenuAc)
        self.pushButton.clicked.connect(self.tiklandi)


        self.pixmap = QPixmap('logo.jpg')
        self.logo.setPixmap(self.pixmap)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ASPARSER"))
        self.logo.setText(_translate("MainWindow", "TextLabel"))
        self.sinif_line.setPlaceholderText(_translate("MainWindow", "00,0,4"))
        self.double_color_checkBox.setText(_translate("MainWindow", "DOUBLE COLOR"))
        self.sample_mod_checkBox.setText(_translate("MainWindow", "SAMPLE MOD"))
        self.box_test_checkBox.setText(_translate("MainWindow", "BOX TEST"))
        self.pushButton.setText(_translate("MainWindow", "Belge Oluştur"))
        self.parti_label.setText(_translate("MainWindow", "PARTİ NUMARASI:"))
        self.aciklama_label_2.setText(_translate("MainWindow", "RESİM:"))
        self.acklama_line.setPlaceholderText(_translate("MainWindow", "(İSTEĞE BAĞLI)"))
        self.ulke_line.setPlaceholderText(_translate("MainWindow", "TR,UK,GE ..."))
        self.ulke_label.setText(_translate("MainWindow", "ÜLKE KODU:"))
        self.size_label.setText(_translate("MainWindow", "SIZE:"))
        self.parti_line.setPlaceholderText(_translate("MainWindow", "1,2,3 ... 999"))
        self.sa_label.setText(_translate("MainWindow", "STANDART/ARC"))
        self.size_line.setPlaceholderText(_translate("MainWindow", "8,9,10,11,12"))
        self.dosya_sec_pushbutton.setText(_translate("MainWindow", "DOSYA SEÇ"))
        self.sinif_label.setText(_translate("MainWindow", "SINIF NUMARASI:"))
        self.standartRadio.setText(_translate("MainWindow", "STANDART"))
        self.arcRadio.setText(_translate("MainWindow", "ARC"))
        self.aciklama_label.setText(_translate("MainWindow", "AÇIKLAMA:"))
        self.parti_eleman_line.setPlaceholderText(_translate("MainWindow", "1,2,3 ... 999"))
        self.lot_label.setText(_translate("MainWindow", "LOT NUMARASI:"))
        self.parti_eleman_label.setText(_translate("MainWindow", "PARTI ELEMAN SAYISI:"))
        self.menu_coklu.setTitle(_translate("MainWindow", "Çoklu Belge Oluştur"))
        self.menu_ikili.setText(_translate("MainWindow", "İkili Belge Oluştur"))
        self.menu_dortlu.setText(_translate("MainWindow", "Dörtlü Belge Oluştur"))
        self.menu_altili.setText(_translate("MainWindow", "Altılı Belge Oluştur"))
        self.menu_sekizli.setText(_translate("MainWindow", "Sekizli Belge Oluştur"))

    def lotMenuAc(self):
        print("lot")

    def dortluMenuAc(self):
        print("Dortlu Menu Tiklandi")
        self.window = QtWidgets.QMainWindow()
        self.ui = dortluyap.Ui_DortluYap()
        self.ui.setupUi(self.window)
        self.window.show()

    def ikiliMenuAc(self):
        sizeInput = self.size_line.text()
        self.window = QtWidgets.QMainWindow()
        self.ui = ikiliyap.Ui_IkiliYap(sizeInput)
        self.ui.setupUi(self.window)
        self.window.show()

    def tiklandi(self):
        self.yukleniyorAc()
        print("Tiklandi")

        ulkeInput = self.ulke_line.text()
        partiInput = self.parti_line.text()
        sinifInput = self.sinif_line.text()
        sizeInput = self.size_line.text()
        lotInput = self.lot_line.text()
        partiElemanInput = int(self.parti_eleman_line.text())
        saInput = "A" if self.arcRadio.isChecked() else "S"
        aciklamaInput = self.acklama_line.text()

        isSample = False
        isBoxTest = False
        isDoubleColor = False


        if (self.sample_mod_checkBox.isChecked()):
            isSample = True #sample modu diger fonksiyonlarda aktiflestirmek icin flag.

        if (self.box_test_checkBox.isChecked()):
            isBoxTest = True

        if(self.double_color_checkBox.isChecked()):
            isDoubleColor = True

        fonksiyon = Functions(ulkekodu=ulkeInput, partiNo=partiInput, classNo=sinifInput, sizeNo=sizeInput, lotNo=lotInput, partidekiEldivenSayisi=partiElemanInput,aciklama=aciklamaInput, isStandart=saInput, isSample=isSample, isBoxTest=isBoxTest, isDoubleColor=isDoubleColor)
        fonksiyon.seriNoOlustur()
        fonksiyon.qrCodeOlustur()#isSample true gitmesi lazim sample durumunda
        fonksiyon.qrCodeEkle()
        fonksiyon.yaziResimBirlesme()

        if (self.sample_mod_checkBox.isChecked()):
            fonksiyon.sampleMod() #sample modu faal hale getirmek

        if(self.double_color_checkBox.isChecked()):
            fonksiyon.doubleColorMod()

        self.yukleniyorKapa()

    def yukleniyorAc(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = yukleniyorPencere.Ui_YukleniyorPencere()
        self.ui.setupUi(self.window)
        self.window.show()

    def yukleniyorKapa(self):
        self.window.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
